var searchData=
[
  ['va_5flist_3003',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['valarray_3004',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valarray_3c_20double_20_3e_3005',['valarray&lt; double &gt;',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['value_5fcompare_3006',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare']]],
  ['vector_3007',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20bool_20_3e_3008',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_3009',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20geometry_3a_3ajarvis_3a_3apoint_20_3e_3010',['vector&lt; geometry::jarvis::Point &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_3011',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int64_5ft_20_3e_3012',['vector&lt; int64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20machine_5flearning_3a_3aneural_5fnetwork_3a_3alayers_3a_3adenselayer_20_3e_3013',['vector&lt; machine_learning::neural_network::layers::DenseLayer &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20operations_5fon_5fdatastructures_3a_3atrie_5foperations_3a_3atnode_20_2a_20_3e_3014',['vector&lt; operations_on_datastructures::trie_operations::Tnode * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20int_20_3e_20_3e_3015',['vector&lt; std::list&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20data_5fstructures_3a_3anode_20_3e_20_3e_3016',['vector&lt; std::shared_ptr&lt; data_structures::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20node_20_3e_20_3e_3017',['vector&lt; std::shared_ptr&lt; Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20range_5fqueries_3a_3apersegtree_3a_3anode_20_3e_20_3e_3018',['vector&lt; std::shared_ptr&lt; range_queries::perSegTree::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_3019',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avalarray_3c_20double_20_3e_20_3e_3020',['vector&lt; std::valarray&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20int_20_3e_20_3e_3021',['vector&lt; std::vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_3022',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_3023',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_3024',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20x_20_3e_3025',['vector&lt; X &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]]
];
